### ISSUE TITLE
is it possible to inject spanId and traceId from @opentelemetry/instrumentation-pino?

### ISSUE THREAD

**Issue by sergei-aivazian** [Vunovati/pino-opentelemetry-transport#16] opened 2023-08-11 13:10 UTC
It looks like that this transport doesn't send now traceId ansd spanId to otel collector in proper structure?
It sends them as attributes.
Is it possible to add this functionality?

**Comment by Vunovati** [comment] 2023-08-28 13:39
You are correct; thanks for pointing it out. I was aware of this issue but did not document it or create an issue to track it. I assume the problem happens because if you have your Pino auto-instrumented by the OTLP SDK, it will add the spanId and traceId to the global SDK context. Since this Pino transport is running in a worker thread, it has its own global SDK context where this does not get reflected. We need to come up with a clean way to serialize this context across to the worker thread and then restore it from within the transport. It might be as simple as just setting SpandId and ContextId in the SDK when they reach the transport side.



I plan to add this functionality as it is a must-have really. If you are willing to send some code samples with an easy way to reproduce this, it will definitely speed up the process of resolving it.

**Closed** 2023-09-08 14:41 UTC
